//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using Protocol;
    
    public class PanelLoginData : QFramework.UIPanelData
    {
    }
    
    public partial class PanelLogin : QFramework.UIPanel
    {
        private InputField inputFieldAccount;
        private InputField inputFieldPassword;
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            switch (eventId)
            {
                case (int)UIEventEnum.Login.CloseLogin:
                    UIKit.ClosePanel<PanelLogin>();
                    break;
                case (int) UIEventEnum.Login.Login:
                    AccountDto accountDto = new AccountDto(inputFieldAccount.text, inputFieldPassword.text);
                    SocketMsg socketMsg = new SocketMsg((int) OpCode.Account, (int) SubCode.Account.Login, accountDto);

                    SendMsg(new EventMsg(socketMsg,NetEvent.Send));
                    break;
            }
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as PanelLoginData ?? new PanelLoginData();
            // please add init code here
            inputFieldAccount= gameObject.Find<InputField>("InputFieldAccount");
            inputFieldPassword= gameObject.Find<InputField>("InputFieldPassword");
            
            RegisterEvent(UIEventEnum.Login.CloseLogin);
            RegisterEvent(UIEventEnum.Login.Login);
            
            gameObject.Find<Button>("BtnClose").onClick.AddListener(()=>
            {
                SendEvent(UIEventEnum.Login.CloseLogin);
            });
            gameObject.Find<Button>("BtnLogin").onClick.AddListener(() =>
            {
                if (string.IsNullOrEmpty(inputFieldAccount.text)
                    ||string.IsNullOrEmpty(inputFieldPassword.text) )
                {
                    return;
                }
                SendEvent(UIEventEnum.Login.Login);
            });
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
