//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UniRx;

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class PanelPromptData : QFramework.UIPanelData
    {
        public string value;

        public PanelPromptData(string value)
        {
            this.value = value;
        }
    }
    
    public partial class PanelPrompt : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as PanelPromptData ?? new PanelPromptData("");
            // please add init code here
            gameObject.Find<Text>("TxtPrompt").text = mData.value;
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
            Observable.Timer(TimeSpan.FromSeconds(2.0f)).Subscribe(_ =>
            {
                CloseSelf();
            });
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
