//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:24365ddd-ced8-4aed-8e3a-1325c4a349b6
    public partial class PanelUID
    {
        
        public const string NAME = "PanelUID";
        
        [SerializeField()]
        public UnityEngine.UI.Text TxtUID;
        
        private PanelUIDData mPrivateData = null;
        
        public PanelUIDData Data
        {
            get
            {
                return mData;
            }
        }
        
        PanelUIDData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PanelUIDData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            TxtUID = null;
            mData = null;
        }
    }
}
