//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:1ff5b138-ad3e-449a-a92c-adcb19e8554e
    public partial class PanelBg
    {
        
        public const string NAME = "PanelBg";
        
        private PanelBgData mPrivateData = null;
        
        public PanelBgData Data
        {
            get
            {
                return mData;
            }
        }
        
        PanelBgData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PanelBgData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            mData = null;
        }
    }
}
