//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class PanelBgData : QFramework.UIPanelData
    {
    }
    
    public partial class PanelBg : QFramework.UIPanel
    {
        
        
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            
            
            switch (eventId)
            {
                case (int) UIEventEnum.Login.OpenLogin:
                    UIKit.OpenPanel<PanelLogin>(UILevel.Common);
                    break;
                case (int) UIEventEnum.Login.OpenRegist:
                    UIKit.OpenPanel<PanelRegist>(UILevel.Common);
                    break;

                default:
                    break;
            }
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as PanelBgData ?? new PanelBgData();
            
            // please add init code here
            gameObject.Find<Button>("BtnLogin").onClick.AddListener(() =>
            {
                SendEvent(UIEventEnum.Login.OpenLogin);
            });
            gameObject.Find<Button>("BtnRegist").onClick.AddListener(() =>
            {
                SendEvent(UIEventEnum.Login.OpenRegist);
            });
            
            RegisterEvent(UIEventEnum.Login.OpenLogin);
            RegisterEvent(UIEventEnum.Login.OpenRegist);
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
