//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:67b9f7fa-9137-49f1-92e8-74689e798244
    public partial class PanelPrompt
    {
        
        public const string NAME = "PanelPrompt";
        
        private PanelPromptData mPrivateData = null;
        
        public PanelPromptData Data
        {
            get
            {
                return mData;
            }
        }
        
        PanelPromptData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PanelPromptData(""));
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            mData = null;
        }
    }
}
