//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Backcardprefab_prefab
    {
        public const string BundleName = "backcardprefab_prefab";
        public const string BACKCARDPREFAB = "backcardprefab";
    }
    public class Cardback_png
    {
        public const string BundleName = "cardback_png";
        public const string CARDBACK = "cardback";
    }
    public class Cardprefab_prefab
    {
        public const string BundleName = "cardprefab_prefab";
        public const string CARDPREFAB = "cardprefab";
    }
    public class Chat1_ogg
    {
        public const string BundleName = "chat1_ogg";
        public const string CHAT1 = "chat1";
    }
    public class Chat2_ogg
    {
        public const string BundleName = "chat2_ogg";
        public const string CHAT2 = "chat2";
    }
    public class Chat3_ogg
    {
        public const string BundleName = "chat3_ogg";
        public const string CHAT3 = "chat3";
    }
    public class Clubeight_png
    {
        public const string BundleName = "clubeight_png";
        public const string CLUBEIGHT = "clubeight";
    }
    public class Clubfive_png
    {
        public const string BundleName = "clubfive_png";
        public const string CLUBFIVE = "clubfive";
    }
    public class Clubfour_png
    {
        public const string BundleName = "clubfour_png";
        public const string CLUBFOUR = "clubfour";
    }
    public class Clubjack_png
    {
        public const string BundleName = "clubjack_png";
        public const string CLUBJACK = "clubjack";
    }
    public class Clubking_png
    {
        public const string BundleName = "clubking_png";
        public const string CLUBKING = "clubking";
    }
    public class Clubnine_png
    {
        public const string BundleName = "clubnine_png";
        public const string CLUBNINE = "clubnine";
    }
    public class Clubone_png
    {
        public const string BundleName = "clubone_png";
        public const string CLUBONE = "clubone";
    }
    public class Clubqueen_png
    {
        public const string BundleName = "clubqueen_png";
        public const string CLUBQUEEN = "clubqueen";
    }
    public class Clubseven_png
    {
        public const string BundleName = "clubseven_png";
        public const string CLUBSEVEN = "clubseven";
    }
    public class Clubsix_png
    {
        public const string BundleName = "clubsix_png";
        public const string CLUBSIX = "clubsix";
    }
    public class Clubten_png
    {
        public const string BundleName = "clubten_png";
        public const string CLUBTEN = "clubten";
    }
    public class Clubthree_png
    {
        public const string BundleName = "clubthree_png";
        public const string CLUBTHREE = "clubthree";
    }
    public class Clubtwo_png
    {
        public const string BundleName = "clubtwo_png";
        public const string CLUBTWO = "clubtwo";
    }
    public class Hearteight_png
    {
        public const string BundleName = "hearteight_png";
        public const string HEARTEIGHT = "hearteight";
    }
    public class Heartfive_png
    {
        public const string BundleName = "heartfive_png";
        public const string HEARTFIVE = "heartfive";
    }
    public class Heartfour_png
    {
        public const string BundleName = "heartfour_png";
        public const string HEARTFOUR = "heartfour";
    }
    public class Heartjack_png
    {
        public const string BundleName = "heartjack_png";
        public const string HEARTJACK = "heartjack";
    }
    public class Heartking_png
    {
        public const string BundleName = "heartking_png";
        public const string HEARTKING = "heartking";
    }
    public class Heartnine_png
    {
        public const string BundleName = "heartnine_png";
        public const string HEARTNINE = "heartnine";
    }
    public class Heartone_png
    {
        public const string BundleName = "heartone_png";
        public const string HEARTONE = "heartone";
    }
    public class Heartqueen_png
    {
        public const string BundleName = "heartqueen_png";
        public const string HEARTQUEEN = "heartqueen";
    }
    public class Heartseven_png
    {
        public const string BundleName = "heartseven_png";
        public const string HEARTSEVEN = "heartseven";
    }
    public class Heartsix_png
    {
        public const string BundleName = "heartsix_png";
        public const string HEARTSIX = "heartsix";
    }
    public class Heartten_png
    {
        public const string BundleName = "heartten_png";
        public const string HEARTTEN = "heartten";
    }
    public class Heartthree_png
    {
        public const string BundleName = "heartthree_png";
        public const string HEARTTHREE = "heartthree";
    }
    public class Hearttwo_png
    {
        public const string BundleName = "hearttwo_png";
        public const string HEARTTWO = "hearttwo";
    }
    public class Ljoker_png
    {
        public const string BundleName = "ljoker_png";
        public const string LJOKER = "ljoker";
    }
    public class Panelbg_prefab
    {
        public const string BundleName = "panelbg_prefab";
        public const string PANELBG = "panelbg";
    }
    public class Panelchat_prefab
    {
        public const string BundleName = "panelchat_prefab";
        public const string PANELCHAT = "panelchat";
    }
    public class Panelcreate_prefab
    {
        public const string BundleName = "panelcreate_prefab";
        public const string PANELCREATE = "panelcreate";
    }
    public class Panelfightbg_prefab
    {
        public const string BundleName = "panelfightbg_prefab";
        public const string PANELFIGHTBG = "panelfightbg";
    }
    public class Panelleftplayer_prefab
    {
        public const string BundleName = "panelleftplayer_prefab";
        public const string PANELLEFTPLAYER = "panelleftplayer";
    }
    public class Panellogin_prefab
    {
        public const string BundleName = "panellogin_prefab";
        public const string PANELLOGIN = "panellogin";
    }
    public class Panelmainbg_prefab
    {
        public const string BundleName = "panelmainbg_prefab";
        public const string PANELMAINBG = "panelmainbg";
    }
    public class Panelmatch_prefab
    {
        public const string BundleName = "panelmatch_prefab";
        public const string PANELMATCH = "panelmatch";
    }
    public class Panelover_prefab
    {
        public const string BundleName = "panelover_prefab";
        public const string PANELOVER = "panelover";
    }
    public class Panelplayerinfo_prefab
    {
        public const string BundleName = "panelplayerinfo_prefab";
        public const string PANELPLAYERINFO = "panelplayerinfo";
    }
    public class Panelprompt_prefab
    {
        public const string BundleName = "panelprompt_prefab";
        public const string PANELPROMPT = "panelprompt";
    }
    public class Panelregist_prefab
    {
        public const string BundleName = "panelregist_prefab";
        public const string PANELREGIST = "panelregist";
    }
    public class Panelrightplayer_prefab
    {
        public const string BundleName = "panelrightplayer_prefab";
        public const string PANELRIGHTPLAYER = "panelrightplayer";
    }
    public class Panelselfplayer_prefab
    {
        public const string BundleName = "panelselfplayer_prefab";
        public const string PANELSELFPLAYER = "panelselfplayer";
    }
    public class Panelsetting_prefab
    {
        public const string BundleName = "panelsetting_prefab";
        public const string PANELSETTING = "panelsetting";
    }
    public class Paneluid_prefab
    {
        public const string BundleName = "paneluid_prefab";
        public const string PANELUID = "paneluid";
    }
    public class Panelup_prefab
    {
        public const string BundleName = "panelup_prefab";
        public const string PANELUP = "panelup";
    }
    public class Sjoker_png
    {
        public const string BundleName = "sjoker_png";
        public const string SJOKER = "sjoker";
    }
    public class Spadeeight_png
    {
        public const string BundleName = "spadeeight_png";
        public const string SPADEEIGHT = "spadeeight";
    }
    public class Spadefive_png
    {
        public const string BundleName = "spadefive_png";
        public const string SPADEFIVE = "spadefive";
    }
    public class Spadefour_png
    {
        public const string BundleName = "spadefour_png";
        public const string SPADEFOUR = "spadefour";
    }
    public class Spadejack_png
    {
        public const string BundleName = "spadejack_png";
        public const string SPADEJACK = "spadejack";
    }
    public class Spadeking_png
    {
        public const string BundleName = "spadeking_png";
        public const string SPADEKING = "spadeking";
    }
    public class Spadenine_png
    {
        public const string BundleName = "spadenine_png";
        public const string SPADENINE = "spadenine";
    }
    public class Spadeone_png
    {
        public const string BundleName = "spadeone_png";
        public const string SPADEONE = "spadeone";
    }
    public class Spadequeen_png
    {
        public const string BundleName = "spadequeen_png";
        public const string SPADEQUEEN = "spadequeen";
    }
    public class Spadeseven_png
    {
        public const string BundleName = "spadeseven_png";
        public const string SPADESEVEN = "spadeseven";
    }
    public class Spadesix_png
    {
        public const string BundleName = "spadesix_png";
        public const string SPADESIX = "spadesix";
    }
    public class Spadeten_png
    {
        public const string BundleName = "spadeten_png";
        public const string SPADETEN = "spadeten";
    }
    public class Spadethree_png
    {
        public const string BundleName = "spadethree_png";
        public const string SPADETHREE = "spadethree";
    }
    public class Spadetwo_png
    {
        public const string BundleName = "spadetwo_png";
        public const string SPADETWO = "spadetwo";
    }
    public class Squareeight_png
    {
        public const string BundleName = "squareeight_png";
        public const string SQUAREEIGHT = "squareeight";
    }
    public class Squarefive_png
    {
        public const string BundleName = "squarefive_png";
        public const string SQUAREFIVE = "squarefive";
    }
    public class Squarefour_png
    {
        public const string BundleName = "squarefour_png";
        public const string SQUAREFOUR = "squarefour";
    }
    public class Squarejack_png
    {
        public const string BundleName = "squarejack_png";
        public const string SQUAREJACK = "squarejack";
    }
    public class Squareking_png
    {
        public const string BundleName = "squareking_png";
        public const string SQUAREKING = "squareking";
    }
    public class Squarenine_png
    {
        public const string BundleName = "squarenine_png";
        public const string SQUARENINE = "squarenine";
    }
    public class Squareone_png
    {
        public const string BundleName = "squareone_png";
        public const string SQUAREONE = "squareone";
    }
    public class Squarequeen_png
    {
        public const string BundleName = "squarequeen_png";
        public const string SQUAREQUEEN = "squarequeen";
    }
    public class Squareseven_png
    {
        public const string BundleName = "squareseven_png";
        public const string SQUARESEVEN = "squareseven";
    }
    public class Squaresix_png
    {
        public const string BundleName = "squaresix_png";
        public const string SQUARESIX = "squaresix";
    }
    public class Squareten_png
    {
        public const string BundleName = "squareten_png";
        public const string SQUARETEN = "squareten";
    }
    public class Squarethree_png
    {
        public const string BundleName = "squarethree_png";
        public const string SQUARETHREE = "squarethree";
    }
    public class Squaretwo_png
    {
        public const string BundleName = "squaretwo_png";
        public const string SQUARETWO = "squaretwo";
    }
}
