//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Protocol;

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class PanelCreateData : QFramework.UIPanelData
    {
    }
    public partial class PanelCreate : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
        }
        
       
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as PanelCreateData ?? new PanelCreateData();
            // please add init code here
            
            BtnCreate.onClick.AddListener(() =>
            {
                if (string.IsNullOrEmpty(InputFieldName.text))
                {
                    SendMsg(new EventMsg("名字不能为空",NetEvent.ReceivePropmpt));
                    return;
                }
                
                SocketMsg socketMsg = SocketMsgPool.Instance.Allocate(
                    (int)OpCode.User, 
                   (int)SubCode.User.CreateUser_CReq,
                    InputFieldName.text
                    );

                NetMgr.Instance.SendMsg(new EventMsg(socketMsg,NetEvent.Send));
            });
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
