//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:7535a0d3-1d84-4eba-8eff-b8e0fd80e0d6
    public partial class PanelSetting
    {
        
        public const string NAME = "PanelSetting";
        
        [SerializeField()]
        public UnityEngine.UI.Toggle ToggleMusic;
        
        [SerializeField()]
        public UnityEngine.UI.Slider SldVolumn;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnExit;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnClose;
        
        private PanelSettingData mPrivateData = null;
        
        public PanelSettingData Data
        {
            get
            {
                return mData;
            }
        }
        
        PanelSettingData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PanelSettingData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ToggleMusic = null;
            SldVolumn = null;
            BtnExit = null;
            BtnClose = null;
            mData = null;
        }
    }
}
