//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:e52a9f30-d5fe-4694-a64a-6def226a0f19
    public partial class PanelCreate
    {
        
        public const string NAME = "PanelCreate";
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputFieldName;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnCreate;
        
        private PanelCreateData mPrivateData = null;
        
        public PanelCreateData Data
        {
            get
            {
                return mData;
            }
        }
        
        PanelCreateData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PanelCreateData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            InputFieldName = null;
            BtnCreate = null;
            mData = null;
        }
    }
}
