//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class PanelMainBgData : QFramework.UIPanelData
    {
    }
    
    public partial class PanelMainBg : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            switch (eventId)
            {
                case (int)UIEventEnum.Main.OpenSetting:
                    UIKit.OpenPanel<PanelSetting>(UILevel.PopUI);
                    break;
                case (int)UIEventEnum.Main.OpenMatch:
                    UIKit.OpenPanel<PanelMatch>();
                    break;
                default:
                    break;
            }
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as PanelMainBgData ?? new PanelMainBgData();
            // please add init code here
            RegisterEvent(UIEventEnum.Main.OpenSetting);
            RegisterEvent(UIEventEnum.Main.OpenMatch);
            
            BtnSetting.onClick.AddListener(() =>
            {
                SendEvent(UIEventEnum.Main.OpenSetting);
            });
            BtnStart.onClick.AddListener(() =>
            {
                SendEvent(UIEventEnum.Main.OpenMatch);
            });
            
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
