//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Protocol;

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class PanelMatchData : QFramework.UIPanelData
    {
    }
    
    public partial class PanelMatch : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            switch (eventId)
            {
                case (int)UIEventEnum.Main.CloseMatch:
                    CloseSelf();
                    break;
                case (int)UIEventEnum.Main.ShowEnterButton:
                    BtnEnter.gameObject.SetActive(true);
                    break;
                default:
                    break;
            }
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as PanelMatchData ?? new PanelMatchData();
            // please add init code here
            RegisterEvent(UIEventEnum.Main.CloseMatch);
            RegisterEvent(UIEventEnum.Main.ShowEnterButton);
            

            BtnCancel.onClick.AddListener(() =>
            {
                SendEvent(UIEventEnum.Main.CloseMatch);
                SocketMsg socketMsg = SocketMsgPool.Instance.Allocate(
                    (int)OpCode.Match,
                    (int)SubCode.Match.Leave_CReq,
                    null
                );
                Debug.Log("退出房间：" + GameModel.Instance.RoomDto.RoomId.ToString());
                SendMsg(new EventMsg(socketMsg,NetEvent.Send));
            });
            
            BtnEnter.onClick.AddListener(() =>
            {
                SceneMgr.Instance.Load(2, () =>
                {
                    UIKit.CloseAllPanel();
                    Debug.Log("进入游戏");
                    UIKit.OpenPanel<PanelUID>(UILevel.PopUI);
                    UIKit.OpenPanel<PanelFightBg>(UILevel.Bg);
                    UIKit.OpenPanel<PanelUp>();
                    UIKit.OpenPanel<PanelSelfPlayer>();
                });
            });
            
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
            SocketMsg socketMsg = SocketMsgPool.Instance.Allocate(
                (int)OpCode.Match,
                (int)SubCode.Match.Enter_CReq,
                null
                );
            SendMsg(new EventMsg(socketMsg,NetEvent.Send));
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
