//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:877a1388-f857-4d83-b407-2d96c7831c38
    public partial class PanelPlayerInfo
    {
        
        public const string NAME = "PanelPlayerInfo";
        
        [SerializeField()]
        public UnityEngine.UI.Text TxtName;
        
        [SerializeField()]
        public UnityEngine.UI.Text TxtLv;
        
        [SerializeField()]
        public UnityEngine.UI.Slider SldExp;
        
        [SerializeField()]
        public UnityEngine.UI.Text TxtBean;
        
        private PanelPlayerInfoData mPrivateData = null;
        
        public PanelPlayerInfoData Data
        {
            get
            {
                return mData;
            }
        }
        
        PanelPlayerInfoData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PanelPlayerInfoData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            TxtName = null;
            TxtLv = null;
            SldExp = null;
            TxtBean = null;
            mData = null;
        }
    }
}
