//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:01f493f8-7431-4a65-bb45-7f715ec7fad7
    public partial class PanelUp
    {
        
        public const string NAME = "PanelUp";
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgCard1;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgCard2;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgCard3;
        
        private PanelUpData mPrivateData = null;
        
        public PanelUpData Data
        {
            get
            {
                return mData;
            }
        }
        
        PanelUpData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PanelUpData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ImgCard1 = null;
            ImgCard2 = null;
            ImgCard3 = null;
            mData = null;
        }
    }
}
