//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:60288c9e-edf0-4b82-9e56-86c76bccea34
    public partial class PanelLeftPlayer
    {
        
        public const string NAME = "PanelLeftPlayer";
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgPlayer;
        
        [SerializeField()]
        public UnityEngine.UI.Text TxtState;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgChat;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgCard;
        
        private PanelLeftPlayerData mPrivateData = null;
        
        public PanelLeftPlayerData Data
        {
            get
            {
                return mData;
            }
        }
        
        PanelLeftPlayerData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PanelLeftPlayerData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ImgPlayer = null;
            TxtState = null;
            ImgChat = null;
            ImgCard = null;
            mData = null;
        }
    }
}
