//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:2d289dd4-78cb-4534-b6b1-2f78deac5e0e
    public partial class PanelFightBg
    {
        
        public const string NAME = "PanelFightBg";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnChat;
        
        private PanelFightBgData mPrivateData = null;
        
        public PanelFightBgData Data
        {
            get
            {
                return mData;
            }
        }
        
        PanelFightBgData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PanelFightBgData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnChat = null;
            mData = null;
        }
    }
}
