//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Protocol;

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class PanelLeftPlayerData : QFramework.UIPanelData
    {
    }
    
    public partial class PanelLeftPlayer : QFramework.UIPanel
    {
        private Text txtChat;
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            switch (eventId)
            {
                case (int)UIEventEnum.Fight.LeftReady:
                    TxtState.gameObject.SetActive(true);
                    break;

                #region Chat

                    

                #endregion
                case (int)UIEventEnum.Fight.LeftChat1:
                    txtChat.text = "阿姨你快点呐，别磨磨蹭蹭的";
                    AudioKit.PlaySound("Chat1");
                    ImgChat.gameObject.SetActive(true);
                    this.Delay(3, () =>
                    {
                        ImgChat.gameObject.SetActive(false);
                    });
                    break;
                case (int)UIEventEnum.Fight.LeftChat2:
                    txtChat.text = "给阿姨倒一杯卡布奇诺";
                    AudioKit.PlaySound("Chat2");
                    ImgChat.gameObject.SetActive(true);
                    this.Delay(3, () =>
                    {
                        ImgChat.gameObject.SetActive(false);
                    });
                    break;
                case (int)UIEventEnum.Fight.LeftChat3:
                    txtChat.text = "开始你的炸弹秀";
                    AudioKit.PlaySound("Chat3");
                    ImgChat.gameObject.SetActive(true);
                    this.Delay(3, () =>
                    {
                        ImgChat.gameObject.SetActive(false);
                    });
                    break;
                    
                case (int)UIEventEnum.Fight.HideState:
                    TxtState.gameObject.SetActive(false);
                    break;
            }
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as PanelLeftPlayerData ?? new PanelLeftPlayerData();
            // please add init code here
            RegisterEvent(UIEventEnum.Fight.LeftReady);
            RegisterEvent(UIEventEnum.Fight.LeftChat1);
            RegisterEvent(UIEventEnum.Fight.LeftChat2);
            RegisterEvent(UIEventEnum.Fight.LeftChat3);
            
            //RegisterEvent(UIEventEnum.Fight.HideState);
            
            txtChat = ImgChat.gameObject.Find<Text>("TxtChat");

        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
