//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Protocol;

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class PanelChatData : QFramework.UIPanelData
    {
    }
    
    public partial class PanelChat : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as PanelChatData ?? new PanelChatData();
            // please add init code here
            BtnChat1.onClick.AddListener(() =>
            {
                SocketMsg socketMsg = SocketMsgPool.Instance.Allocate(
                    (int)OpCode.Chat,
                    (int)SubCode.Chat.CReq,
                    1
                );
                SendMsg(new EventMsg(socketMsg,NetEvent.Send));
                SendEvent(UIEventEnum.Fight.SelfChat1);
                
            });  
            BtnChat2.onClick.AddListener(() =>
            {
                SocketMsg socketMsg = SocketMsgPool.Instance.Allocate(
                    (int)OpCode.Chat,
                    (int)SubCode.Chat.CReq,
                    2
                );
                SendMsg(new EventMsg(socketMsg,NetEvent.Send));
                SendEvent(UIEventEnum.Fight.SelfChat2);
                
            }); 
            BtnChat3.onClick.AddListener(() =>
            {
                SocketMsg socketMsg = SocketMsgPool.Instance.Allocate(
                    (int)OpCode.Chat,
                    (int)SubCode.Chat.CReq,
                    3
                );
                SendMsg(new EventMsg(socketMsg,NetEvent.Send));
                SendEvent(UIEventEnum.Fight.SelfChat3);
                
            });
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
