//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:2374c69c-bff8-4a4d-807f-bfc3585e438d
    public partial class PanelChat
    {
        
        public const string NAME = "PanelChat";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnChat1;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnChat2;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnChat3;
        
        private PanelChatData mPrivateData = null;
        
        public PanelChatData Data
        {
            get
            {
                return mData;
            }
        }
        
        PanelChatData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PanelChatData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnChat1 = null;
            BtnChat2 = null;
            BtnChat3 = null;
            mData = null;
        }
    }
}
